name: Update GitHub Activity

on:
  schedule:
    - cron: '0 */6 * * *'  # runs every 6 hours
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
